/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.11 src/model/reactor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/reactor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Icosphere002.geometry} material={nodes.Icosphere002.material} rotation={[0, 0, 2.483]} />
      <mesh geometry={nodes.Icosphere003.geometry} material={nodes.Icosphere003.material} rotation={[0, 0, 2.483]} />
      <mesh geometry={nodes.Icosphere004.geometry} material={nodes.Icosphere004.material} rotation={[0, 0, 2.483]} />
    </group>
  )
}

useGLTF.preload('/reactor.glb')
